"""Integration credential decryption — byte-compatible with the API's
encryptSecret (apps/api/src/common/crypto.ts): scrypt(masterKey,
'gros-credentials', N=16384, r=8, p=1) -> AES-256-GCM, blob = iv|tag|cipher.
Cross-language compatibility is pinned by tests/test_credentials.py with a
vector generated by the Node implementation.
"""

from __future__ import annotations

import hashlib
import json
import os

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from .settings import get_settings


def _key(master_key: str) -> bytes:
    return hashlib.scrypt(
        master_key.encode(), salt=b"gros-credentials", n=16384, r=8, p=1, dklen=32,
        maxmem=64 * 1024 * 1024,
    )


def decrypt_credentials(blob: bytes, master_key: str | None = None) -> dict[str, str]:
    mk = master_key or get_settings().credentials_master_key
    iv, tag, cipher = blob[:12], blob[12:28], blob[28:]
    plaintext = AESGCM(_key(mk)).decrypt(iv, cipher + tag, None)
    data: dict[str, str] = json.loads(plaintext.decode())
    return data


def encrypt_credentials(creds: dict[str, str], master_key: str | None = None) -> bytes:
    mk = master_key or get_settings().credentials_master_key
    iv = os.urandom(12)
    sealed = AESGCM(_key(mk)).encrypt(iv, json.dumps(creds).encode(), None)
    cipher, tag = sealed[:-16], sealed[-16:]
    return iv + tag + cipher
